export const customStyles = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255, 255, 255, 0.25)",
  },
  content: {
    top: "50%",
    left: "50%",
    right: "auto",
    bottom: "auto",
    marginRight: "-50%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "#A1A9AB",
    color: "black",
    border: "2px solid orange",
    borderRadius: "7px 7px 7px 7px",
    boxShadow: "-7px -7px 17px 7px #4D4D4D",
    maxWidth: "800px",
    maxHeight: "95%",
    WebkitOverflowScrolling: "touch",
  },
};
